export default {
    COM: "COM",
    É: "É",
    IGUAL: "IGUAL",
    ESTRUTURA: "ESTRUTURA",
    IDENTIFICADOR: "IDENTIFICADOR",
    NÚMERO: "NÚMERO",
    UM: "UM",
    UNS: "UNS",
    UMA: "UMA",
    UMAS: "UMAS",
    O: "O",
    OS: "OS",
    A: "A",
    AS: "AS",
    PARA: "PARA",
    RETORNE: "RETORNE",
    PARE: "PARE",
    SE: "SE"
}
